config/routes.rb
Litterbox::Application.routes.draw do

  devise_for :cats
  resources :cats, :only => :show

  
  root :to => 'home#index'
  
  match 'about' => 'home#about'
  match 'contact' => 'home#contact'
  match 'feed' => 'home#feed'

end

app/models/cat.rb
class Cat
  include Mongoid::Document
  include Mongoid::Paperclip
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  #the stuff we want
  
  field :name, :type => String
  validates_presence_of :name
  field :age, :type => Integer, :default => 20
  field :gender, :type => String
  field :orientation, :type => String
  field :hometown, :type => String
  field :looking_for, :type => String
  field :relationship_status, :type => String
  field :religious_views, :type => String
  field :interests, :type => String
  field :food, :type=> String
  field :picture, :type => String

  has_mongoid_attached_file(:avatar, {:styles => 
    {:thumb => ['150x150', :jpg],
     :medium => ['300x300', :jpg]}, :default_url => "/images/:style/missing.png"})
  attr_accessible :avatar 

  attr_accessible :name, :age, :gender, :orientation, :hometown,
  :looking_for, :relationship_status, :religious_views, :interests,
  :food, :picture

  attr_accessible :email, :password, :password_confirmation, :remember_me


  ## Encryptable
  # field :password_salt, :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :authenticate_cat!

  def show
    @cat = Cat.find(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @message = ""
  end

  def create
    @message = params[:message]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_filter :authenticate_cat!

  def index
    if cat_signed_in? 
      redirect_to "/feed"
      #cat_path(current_cat)
    end
  end

  def feed
    @cats = Cat.all
  end

  def contact
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cat_notifier/new_message.text.erb
You have received a message from <%= @cat.name %> on Meowspace!


<%= @message.body %>


To view their profile and meow back, check out <%= link_to("their profile!",user_path(@cat)) %>

app/views/cats/show.html.erb
<h1><%= @cat.name %>'s Profile 
<a class="btn btn-primary btn-medium">Meow @ me! &hearts; </a></h1>  
 
<br></br>
<p><%= image_tag(current_cat.avatar.url(:medium)) %></p>

<p>Name: <%= @cat.name %></p>
<p>Age: <%= @cat.age %></p>
<p>Gender: <%= @cat.gender %></p>
<p>Orientation: <%= @cat.orientation %></p>
<p>Hometown: <%= @cat.hometown %></p>
<p>Looking for: <%= @cat.looking_for %></p>
<p>Status: <%= @cat.relationship_status %></p>
<p>Religious views: <%= @cat.religious_views %></p>
<p>Interests: <%= @cat.interests %></p>
<p>Favorite food: <%= @cat.food %></p>


  

app/views/home/about.html.erb
<p>Hello</p>

app/views/home/contact.html.erb
<p>hi</p>

app/views/home/feed.html.erb
<% @cats.each do |cat| %>
<div><%= link_to(image_tag(cat.avatar(:thumb)),cat_path(cat)) %> 
  <%= link_to(cat.name, cat_path(cat)) %>
</div>
<% end %>

app/views/home/index.html.erb
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
	<h1>Welcome to <accent>MeowSpace</accent>&hearts; !</h1>
	<p>The world's premiere dating site for cats. Sign kitty up today! </p>
    <br></br>
    <p> <a class="btn btn-primary btn-large" href="/cats/sign_up"> Sign up &raquo; </a></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Meowspace</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>
	<!-- Le styles -->
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style> 
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
   </head>


<body>

	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">MeowSpace &hearts;</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><%= link_to("Home",root_path) %></li>
              
               <li>
                <% if cat_signed_in? %>
            	<%= link_to("My Profile", cat_path(current_cat)) %> 
		<li><%= link_to("Edit",edit_cat_registration_path(current_cat)) %></li>
		<% end %>              
              
              
            </ul>
            
           
	    <% if cat_signed_in? %>
            <p class="navbar-text pull-right">Logged in as <%= link_to(current_cat.name, cat_path(current_cat)) %> : <%= link_to('Logout', destroy_cat_session_path, :method=>'delete') %> </p>
	    <% else %>
	    	<p class ="navbar-text pull-right"><%= link_to("Sign in", new_cat_session_path) %></p>
	    <% end %>
	   	  
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
	<div class="container">


		<%= yield %> 


		<hr>
		<footer>
        	<p>&copy; <a href="https://github.com/cmoscardi"> cmoscardi </a> & <a href="https://github.com/sbchou"> sbchou</a> 2012 | <a href="../about.html">ABOUT</a></p>
        </footer>	

	</div> <!-- /container -->


  </body>
</html>